name: Sample workflow
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -a
          echo ""
          git branch -a

      - uses: actions/checkout@v4
        with:
          repository: test1
      - run: |
          ls -a
          echo ""
          git branch -a