name: Sample workflow
on: 
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -a
          echo ""
          git branch

      - uses: actions/checkout@v4
        with:
          ref: test1
      - run: |
          ls -a
          echo ""
          git branch