
name: main

on: 
  push:
  workflow_dispatch:

jobs:
  call-test1-1:
      uses: "./.github/workflows/test1.yml"

  call-test1-2:
        uses: "./.github/workflows/test1.yml"
        with:
          text: 'test3'

  call-test1-3:
        uses: "./.github/workflows/test1.yml"
        with:
          text: 'test3'

  call-test2-1:
        uses: "./.github/workflows/test2.yml"
        with:
          text: 'ファイル2のテスト１'