name: Sample workflow
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -a
          echo ""
          git log

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          ls -a
          echo ""
          git log

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          ls -a
          echo ""
          git log