
name: main

on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
  
  call-test1-1:
      uses: "./.github/workflows/test1.yml"

  call-test1-2:
        uses: "./.github/workflows/test1.yml"
        needs: call-test1-1
        with:
          text: 'test2'

  call-test1-3:
        uses: "./.github/workflows/test1.yml"
        needs: call-test1-2
        with:
          text: 'test3'

  call-test2-1:
        uses: "./.github/workflows/test2.yml"
        with:
          text: 'ファイル2のテスト１'