name: Sample workflow
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo $PWD
          echo ""
          echo ls -la
          echo ""
          git branch --contains
          echo ""
          git branch
