
name: Run Build

on: [push]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

      - name: test1
        uses: "./.github/workflows/test1.yml"

      - name: test2
        uses: "./.github/workflows/test1.yml"
        with:
          text: 'test2'

      - name: test3
        uses: "./.github/workflows/test1.yml"
        with:
          text: 'test3'

      - name: test3
        uses: "./.github/workflows/test2.yml"
        with:
          text: 'ファイル2のテスト１'