name: test1YML

on:
  workflow_call:
    inputs:
      text:
        description: 'mainから値を受け取るテスト'
        default: 'defaultです'
        required: false
        type: string

jobs:
  cild1:
    runs-on: ubunt-latest
    steps:
      - name: テスト
        run: |
          echo ${{inputs.text}}

