name: Run Deploy

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Run Deploy - Run Testsが成功した後に実行"