name: test

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  run-test1:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo "Run Test後に実行"
