name: test2YML

on:
  workflow_call:
    inputs:
      text:
        description: 'mainから値を受け取るテスト'
        default: 'defaultです'
        required: false
        type: string

jobs:
  cild2:
    runs-on: ubunt-latest
    steps:
      - name: テスト2
        run: |
          echo ${{inputs.text}}
